#Given two strings s and t which consist of only lowercase letters.
#
#String t is generated by random shuffling string s and then add one more letter at a random position.
#
#Find the letter that was added in t.
class Solution(object):
    def findTheDifference(self, s, t):
		"""
		:type s: str
		:type t: str
		:rtype: str
		"""
		s=sorted(s)
		t=sorted(t)
		for i in xrange(len(s)):
			if s[i]!=t[i]:
				return t[i]
		return t[-1]